import type { Metadata } from "next";
import { Manrope, Italiana } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {  ToastContainer } from "react-toastify";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800"],
  display: "swap",
  variable: "--font-manrope",
});

const italiana = Italiana({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-italiana",
});

export const metadata: Metadata = {
  title: "bacteria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.variable} ${italiana.variable} antialiased font-primary`}>
          <ToastContainer
            position="top-right"
            autoClose={4000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored" 
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
